spring:
  profiles:
    active: dev
  application:
    name: sfl-batch-excel
  jackson:
    serialization: true
  batch:
    job:
      enabled: false
  http:
    multipart:
      max-request-size: 64MB
      max-file-size: 64MB

server:
  port: 8007

logging:
  file: /var/logs/sfl-batch-excel.log
